#!/bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
compton --config /home/kali/.config/compton/compton.conf &
feh --bg-fill /home/kali/Pictures/wallpaper.jpg &
wmname LG3D &
~/.config/polybar/launch.sh --colorblocks &
_JAVA_AWT_WM_NONREPARENTING=1

bspc config pointer_modifier mod1

# Keyboard em Português
setxkbmap pt
# Classic BSPWM

bspc monitor -d I II III IV V VI

bspc config border_width 3
bspc config window_gap 12
bspc config focused_border_color "#591c96"
bspc config normal_border_color "#3d3d3d"

bspc config split_ratio 0.5
bspc config automatic_scheme alternate
# bspc config initial_polarity second_child
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
